const data = {
  products: [
    {
      _id: '1',
      name: 'Hanes Mens Sweatshirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: '40',
      brand: 'Hanes',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Hanes Mens Sweatshirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: '50',
      brand: 'Hanes',
      rating: 4.0,
      numReviews: 6,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Hanes Mens Sweatshirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: '75',
      brand: 'Hanes',
      rating: 5.0,
      numReviews: 4,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Hanes Mens Sweatshirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: '35',
      brand: 'Hanes',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Hanes Mens Sweatshirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: '85',
      brand: 'Hanes',
      rating: 5.0,
      numReviews: 1,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Hanes Mens Sweatshirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: '100',
      brand: 'Hanes',
      rating: 4.7,
      numReviews: 20,
      description: 'high quality product',
    },
  ],
};

export default data;
